FROM oraclelinux:9

# MySQL's version to use such as: 8.0.42, 8.4.6, etc
ARG MYSQL_VERSION="8.4.6"

RUN yum update -y && \
	yum install -y 'dnf-command(config-manager)' && \
	yum config-manager --set-enabled ol9_codeready_builder && \
	yum install -y \
		bind-utils \
		bison \
		cmake3 \
		cyrus-sasl-devel \
		git \
		krb5-devel \
		libaio-devel \
		libcurl-devel \
		libfido2-devel \
		libtirpc-devel \
		libudev-devel \
		ncurses-devel \
		numactl-devel \
		openldap-devel \
		openssl-devel \
		perl \
		perl-JSON rpcgen \
		rpm-build \
		time \
		gcc-toolset-12-annobin-annocheck \
		gcc-toolset-12-annobin-plugin-gcc \
		gcc-toolset-12-binutils  \
		gcc-toolset-12-dwz \
		gcc-toolset-12-gcc \
		gcc-toolset-12-gcc-c++ \
		wget \
		zlib-devel && \
    yum clean all

WORKDIR /development/

# Download MySQL source, extract and setup the directories
RUN wget https://cdn.mysql.com/Downloads/MySQL-${MYSQL_VERSION%.*}/mysql-$MYSQL_VERSION.tar.gz && \
    tar xzf mysql-$MYSQL_VERSION.tar.gz && \
    rm mysql-$MYSQL_VERSION.tar.gz && \
    ln -sf mysql-$MYSQL_VERSION mysql

#RUN mkdir -p /development/mysql/plugin/mysqldays/

#COPY src/ /development/mysql/plugin/mysqldays/

WORKDIR /development/mysql/bld

# Building process
RUN cmake3 -DBUILD_CONFIG=mysql_release -DINSTALL_LAYOUT=RPM -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/development/boost/ ..

ENTRYPOINT ["sleep", "infinity"]
