{
 "title": "MySQL days Plugin - Operations",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Plugin - Global Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "mysql_global_status_mysqldays_total_queries",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% of special queries",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_mysqldays_total_special_queries / mysql_global_status_mysqldays_total_queries",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total time (ms) inside the plugin",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "mysql_global_status_mysqldays_total_time_us / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Processing time per query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "mysql_global_status_mysqldays_total_time_us / mysql_global_status_mysqldays_total_queries",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugin - System Variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plugin enabled?",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mysql_global_variables_mysqldays_enabled",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}